tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "aws/tap"

brew "zsh"
brew "git"
brew "git-lfs"
brew "cocoapods"
brew "watchman" 
brew "node"

cask "zulu11"
cask "slack"
cask "visual-studio-code"
cask "android-studio"
cask "iterm2"